version: "3.9"

services:
  smile_simulation:
    container_name: smile_simulation
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${XAUTHORITY}:/tmp/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/home/ros/src
    privileged: true
    tty: true
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.Xauthority
      - ROS_DOMAIN_ID=34
    devices:
      - /dev/tty*:/dev/tty*
    network_mode: host
    command: tail -f /dev/null
    restart: always