apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory-simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factory-simulation
  template:
    metadata:
      labels:
        app: factory-simulation
    spec:
      containers:
      - name: factory-simulation
        image: vaskostara/factory-simulation:latest
        volumeMounts:
        - mountPath: /tmp/.X11-unix
          name: x11-socket
          readOnly: false
        ports:
        - containerPort: 11345
        - containerPort: 11311
        env:
          - name : SDL_VIDEODRIVER
            value : "x11"
          - name : XAUTHORITY
            value : "/tmp/.docker.xauth"
          - name : DISPLAY
            value : ":1"
          - name : QT_X11_NO_MITSHM
            value : "1"
          - name : ROS_DOMAIN_ID
            value : "39"
          - name : GAZEBO_MASTER_URI
            value : "http://0.0.0.0:11345"
          - name : ROS_MASTER_URI
            value : "http://0.0.0.0:11311/"
          - name: SIM_ENV
            value : CICD
        command: ["/bin/bash"]
        args: ["-c", "cd /home/ros/src/; ./start.sh build; SIM_ENV=CICD ./start.sh sim"]
      volumes:
        - name: x11-socket
          hostPath:
            path: /tmp/.X11-unix


