apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: camera-processor
  template:
    metadata:
      labels:
        app: camera-processor
    spec:
      containers:
      - name: factory-simulation
        image: vaskostara/factory-simulation:latest
        env:
          - name : ROS_DOMAIN_ID
            value : "39"
          - name : ROS_MASTER_URI
            value : "http://sim-service:11311/"
          - name : GAZEBO_MASTER_URI
            value : "http://sim-service:11345"
        command: ["/bin/bash"]
        args: ["-c", "./start.sh build; ./start.sh screenshot 164"]
