apiVersion: v1
kind: Service
metadata:
 name: sim-service
spec:
 ports:
  - name: ros
    port: 11311
    targetPort: 11311
  - name: gazebo
    port: 11345
    targetPort: 11345
 selector:
   app: factory-simulation
 type: ClusterIP